const texts = {
"spanish": 
    { "shortDescription" : "Gripper es un proyecto que pone en tensión diversos estilos musicales, teniendo en cuenta su tradición e historia, experimentando con las diversas formas de la canción, el lenguaje contemporáneo, la improvisación, la performance, vinculándose con el arte digital, el livecoding y el video arte. Gripper está inspirado por apropiaciones locales de géneros foráneos, y busca la hibridación desde una mirada latinoamericanista y reflexiva sobre la estética moderna.",
        "longDescription":'El proyecto empezó hace diez años en Alta Gracia, Córdoba, Argentina de la mano de Mariano Sosa Alvarez. En principio era un proyecto pensado para realizar producciones sin necesidad de tocarse en vivo. En 2018 el proyecto empezó a realizar conciertos de la mano de Mariano Alvarez en solitario. Luego se suma Pablo Gonzalez en guitarra en 2022 y ese mismo año, Agustin Ghietti en batería. Actualmente es una formación de cuatro performers siendo Ghietti Agustin en batería y voz, Pablo Gonzalez en guitarra, Karen Palacio en visuales y Mariano Sosa Alvarez en bajo y voz. Gripper cuenta con 25 producciones y múltiples colaboraciones. Se ha presentado en vivo en el acto de la asociación de músicos de Alta Gracia (ASOMA) en 2018, en Fundación Holderlin en José de la Quintana (2018), en la Expo Mutante en Muta Espacio, en vinculación con la Municipalidad de Córdoba (2022) y sucesivas veces en la Kamehouse de barrio Alberdi, Córdoba el mismo año. La propuesta se sitúa en la reflexión de la modernidad mediante el concepto de hauntology de Mark Fisher, que pone en tensión la temporalidad en el cruce de estilos musicales. El autoexotismo como revisión de la identidad en la prática musical desde una mirada latinoamerica en la perspectiva de Izquierdo Konig. Y el radical music que plantea una música que no pertenece ni a la academia, ni a la música popular pero que sin embargo se nutre; y nutre a ambas (falta el autor).',
    },
"english": 
    { "shortDescription" : "Gripper is a project based in Córdoba, Argentina. It engages with various musical styles, taking into account their tradition and history, while experimenting with different forms of song, contemporary language, improvisation, performance, and connecting with digital art, live coding, and video art. Gripper is inspired by local appropriations of foreign genres and seeks hybridization from a Latin American, critical, and reflective perspective on modern aesthetics.",
    "longDescription" :'The project started ten years ago in Alta Gracia, Córdoba, Argentina, under the guidance of Mariano Sosa Alvarez. Initially, it was conceived as a project for producing music without the need for live performances. In 2018, Mariano Alvarez began performing concerts as a solo artist. Later that year, Pablo Gonzalez joined on guitar, and in the same year, Agustin Ghietti joined on drums. Currently, the group consists of four performers: Agustin Ghietti on drums and vocals, Pablo Gonzalez on guitar, Karen Palacio on visuals, and Mariano Sosa Alvarez on bass and vocals. Gripper has released 25 productions and has engaged in multiple collaborations.<br><br>The project has performed live at the Alta Gracia Musicians Association event (ASOMA) in 2018, at Fundación Holderlin in José de la Quintana in 2018, at Expo Mutante in Muta Espacio in collaboration with the Municipality of Córdoba in 2022, and multiple times at Kamehouse in the Alberdi neighborhood, Córdoba, in the same year.<br><br>The concept behind the project revolves around the reflection on modernity through Mark Fishers hauntology, which examines the tension between temporalities in the intersection of musical styles. It explores auto-exoticism as a revision of identity in musical practice from a Latin American perspective, influenced by Izquierdo Konig. Additionally, it embraces the concept of radical music, which proposes a form of music that does not belong to either the academy or popular music, yet draws inspiration from and enriches both (author missing).'},
}
